targets:
  $default:
    builders:
      freezed:
        enabled: true
        generate_for:
          include:
            - lib/data/models/**.dart
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/data/models/**.dart
        options:
          explicit_to_json: true
          include_if_null: false